api_platform:
    mapping:
        paths: [
            '%kernel.project_dir%/src/Project/ApiResource',
            '%kernel.project_dir%/src/Task/ApiResource',
        ]
    show_webby: false
    title: 'Projects and Tasks'
    description: 'Simple application used to manage projects and tasks'
    version: 1.0.0
    defaults:
        extra_properties:
            standard_put: true
        collect_denormalization_errors: true
        pagination_items_per_page: 20
        pagination_maximum_items_per_page: 100
        pagination_client_items_per_page: true
