services:
  app:
    container_name: projects-and-tasks-app
    build:
      context: app
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    volumes:
      - ../:/var/www/app
      - ./app/etc/php.ini:/usr/local/etc/php/php.ini
      - ./app/etc/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./app/etc/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      PHP_IDE_CONFIG: serverName=projects-and-tasks-app
  postgres:
    container_name: projects-and-tasks-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  caddy:
    container_name: projects-and-tasks-caddy
    image: caddy:2.6
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ../:/var/www/app
      - caddy_data:/data
      - caddy_config:/config

volumes:
  postgres:
  caddy_data:
  caddy_config:
